
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kimiyow Blog '
theme = "beautifulhugo"


[menu]
  [[menu.main]]
    identifier = "post1"
    name = "❤︎ Practica 0"
    url = "/posts/post1/"
    weight = 1

  [[menu.main]]
    identifier = "post2"
    name = "❤︎ Practica 1"
    url = "/posts/post2/"
    weight = 2


[params]
  subtitle = "꒷꒦︶꒷꒦︶ ๋ ࣭ ⭑꒷꒦"
  dateformat = "2006-01-02"
  hidecredits = true 
  hidecopyright = false
  customCSS = ["css/custom.css"]

[[params.social]]
  name = "github"
  url = "https://github.com/kimiyow"
