
baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Kimiyow Blog '
theme = "beautifulhugo"


[menu]
  [[menu.main]]
    identifier = "post1"
    name = "❤︎ Practica 0"
    url = "/post/post1/"
    weight = 1

  [[menu.main]]
    identifier = "post2"
    name = "❤︎ Practica 1"
    url = "/post/post2/"
    weight = 2

  [[menu.main]]
    identifier = "post3"
    name = "❤︎ Practica 2"
    url = "/post/post3/"
    weight = 3

  [[menu.main]]
    identifier = "post4"
    name = "❤︎ Practica 3"
    url = "/post/post4/"
    weight = 4

  [[menu.main]]
    identifier = "post6"
    name = "❤︎ Practica 4"
    url = "/post/post6/"
    weight = 5


[params]
  subtitle = "꒷꒦︶꒷꒦︶ ๋ ࣭ ⭑꒷꒦"
  dateformat = "2006-01-02"
  hidecredits = true 
  hidecopyright = false
  customCSS = ["css/custom.css"]

[[params.social]]
  name = "github"
  url = "https://github.com/kimiyow"
